apiVersion: v2
name: opentelemetry-collector
version: 1.0.0
maintainers:
  - name: Samuel Arogbonlo
    email: samuel.arogbonlo@p2p.org
dependencies:
  - name: opentelemetry-collector
    version: "0.117.0"  
    repository: "https://open-telemetry.github.io/opentelemetry-helm-charts"